int* left = new int[4];
    left[0] = 2;
    left[1] = 3;
    left[2] = 6;
    left[3] = 54;
    int* right = new int[5];
    right[0] = 4;
    right[1] = 6;
    right[2] = 8;
    right[3] = 10;
    right[4] = 125;
    deleteArray(left);
    deleteArray(right);